// mod d4;
// mod d5;
// mod d6;
// mod d7;
// mod d8;
// mod d9;
// mod d10;
// mod d11;
// mod d12;
// mod d13;
mod d14;
// mod d15;
// mod d16;
// mod d17;
// mod d18;
// mod d19;
// mod d20;
// mod d21;
// mod d22;
// mod d23;
// mod d24;
// mod d25;
// mod test;

fn main() {
    // println!("Day4:");
    // d4::run();
    // println!("Day5:");
    // d5::run();
    // println!("Day6:");
    // d6::run();
    // println!("Day7:");
    // d7::run();
    // println!("Day8:");
    // d8::run();
    // println!("Day9:");
    // d9::run();
    // println!("Day10:");
    // d10::run(); 
    // println!("Day11:");
    // d11::run();
    // d12::run();
    // d13::run();
    d14::run();
    // println!("Day15:");
    // d15::run();
    // println!("Day16:");
    // d16::run();
    // println!("Day17:");
    // d17::run();
    // println!("Day18:");
    // d18::run();
    // println!("Day19:");
    // d19::run();
    // println!("Day20:");
    // d20::run();
    // println!("Day21:");
    // d21::run();
    // println!("Day22:");
    // d22::run();
    // println!("Day23:");
    // d23::run();
    // println!("Day24:");
    // d24::run();
    // println!("Day25:");
    // d25::run();
    // println!("Test:");
    // test::run();
}