[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
function_name = "0.3"
itertools = "0.10.5"
num = "0.4.0"
lazy_static = "1.4.0"