// mod d1_2021;
// mod d1;
// mod d2;
// mod d3;
// mod d4;
// mod d5;
// mod d6;
// mod d7;
// mod d8;
// mod d9;
// mod d10;
// mod d11;
// mod d12;
// mod d13;
mod d14;
//mod test;

fn main() {
    // println!("Day1 (2021):");
    // d1_2021::run();
    // println!("Day1:");
    // d1::run();
    // println!("Day2:");
    // d2::run();
    // println!("Day3:");
    // d3::run();
    // println!("Day4:");
    // d4::run();
    // println!("Day5:");
    // d5::run();
    // println!("Day6:");
    // d6::run();
    // println!("Day7:");
    // d7::run();
    // println!("Day8:");
    // d8::run();
    // println!("Day9:");
    // d9::run();
    // println!("Day10:");
    // d10::run();
    // println!("Day11:");
    // d11::run();
    // println!("Day12:");
    // d12::run();
    // println!("Day13:");
    // d13::run();
    println!("Day14:");
    d14::run();
    // println!("Test:");
    // test::run();
}